### ISSUE TITLE
Can you upload the latest version?

### ISSUE THREAD

**Issue by LuxuryPanda** [honghe7412/Color-Hole-3D#1]
The version that you uploaded is the v1.0, can you please upload the latest one?

**Comment by honghe7412** [comment]
> The version that you uploaded is the v1.0, can you please upload the latest one?

Sorry, this is a template I bought, I don't have the latest one

**Comment by LuxuryPanda** [comment]
Do you have other Watermelon's games?

**Comment by honghe7412** [comment]
> Do you have other Watermelon's games?

Yes  Color Bump 3D

**Comment by LuxuryPanda** [comment]
Where can i contact you?

**Comment by honghe7412** [comment]
> Where can i contact you?

Do you need it?  I'll upload it to github in a few days

**Comment by LuxuryPanda** [comment]
Yes, but they haven't published Color Bump 3D

**Comment by honghe7412** [comment]
It's on the office computer,i will upload it to you next Monday ,if I forget, remind me here.

**Comment by honghe7412** [comment]
> Yes i really need it. Thank you very much :D

It's on the office computer,i will upload it to you next Monday ,if I forget, remind me here.

**Comment by LuxuryPanda** [comment]
Do you have other assets of this developer: https://assetstore.unity.com/publishers/41882 ?

**Comment by honghe7412** [comment]
> Do you have other assets of this developer: https://assetstore.unity.com/publishers/41882 ?

The Color Bump 3D has been uploaded to github.

**Comment by LuxuryPanda** [comment]
Thank you very much. Could you give me a way to contact you? Email, or something else

**Comment by honghe7412** [comment]
> Thank you very much. Could you give me a way to contact you? Email, or something else

Tencent email：594514149@qq.com

**Comment by LuxuryPanda** [comment]
I wrote an email to you
